# format
# [inervention key]: [utilization reduction factor]

savings:
  t2d: 0.65
  ht: .5
  depression: .8

desc_long:
  ht: 'Follow kidney foundaion guidelines for aggressive treatment'
  t2d: 'Follow kidney foundaion guidelines for aggressive treatment'
  palliative: 'Discuss and provide medication to ease pain and provide comfort'
  educate_engage: 
    delay_plan: 'Discuss diet and exercise. Also emphasize that we can halt progress of CKD at this stage.'
    transition_plan: 'Talk to patient about at-home PD or HD'
    smart_dialysis_plan: 'Discuss desicion wrt. palliaive care vs. dialysis, emphasizing there is little evidence for outcomes benefit with dialysis at this stage. Also discuss patient on benefits with home dialysis and the simplicity of it. Emphasize that it is not hard at all.'
  nephro_engage:
    transition_plan: 'Goal is to Goal is to get graft or fistula + home dialysis'
    smart_dialysis_plan: 'Discuss desicion wrt. palliaive care vs. dialysis, emphasizing there is little evidence for outcomes benefit with dialysis at this stage.'